name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: 1.15.3
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - run: npm i
      - run: deno run -A build.ts
      - run: zip -r chrome.zip chrome

      - name: Release
        if: startsWith(github.ref, 'refs/tags/v') && github.repository == 'zhmushan-zone/translator_extension'
        uses: softprops/action-gh-release@v1
        with:
          files: chrome.zip
          token: ${{ secrets.GITHUB_TOKEN }}